name: First_Name Last_Name
title: First_Name Last_Name Personal Website
twitter_uname: fik7ri
instagram_uname: f7_______g
github_uname: f7g

sass:
  sass_dir: /assets/stylesheets/_sass
baseurl: /jekyllin
exclude: ['README.md']
